server:
  servlet:
    context-path: /send-flow/api
spring:
  application:
    name: send flow
  datasource:
    url: jdbc:mysql://localhost:3306/sendflow
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: ${SECRET}
  access-token-expiration: 10000000
  refresh-token-expiration: 2000000